name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SCHEME: "Widget Examples"
  IOS_SDK: "iphonesimulator"
  IOS_DESTINATION: "platform=iOS Simulator,name=Any iOS Simulator Device,OS=latest"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1

  build:
    runs-on: macos-13
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Swift
      uses: slashmo/install-swift@v0.4.0
      with:
        version: swift-5.9-DEVELOPMENT-SNAPSHOT-2023-07-04-a
    - run: ls /Applications
    - run: sudo xcode-select -s '/Applications/Xcode_15.0.app/Contents/Developer'
    - name: Build
      run: |
        xcodebuild clean build \
          -scheme "$SCHEME" \
          -sdk "$IOS_SDK" \
          -destination "$IOS_DESTINATION" \
          CODE_SIGNING_ALLOWED=NO
